### ISSUE TITLE
Time Zone problem

### ISSUE THREAD

**Issue by hallard** [dragondaud/myClock#1]
Hi  There,

First upload, very nice version.

just some comments:

- setting timezone to "2" or "Europe/Paris" never took the correct time zone for me, was always 2 hours behind as soon as I registered to TimeZoneDB and put the key, worked fine
- temperature from openweather is displayed in Fahrenheit, no option to °C? may be add unit type in json config to allow choosing imperial or metric (and change call to ow)
- Luminosity threshold, I'm not sure to understand what to set there. What about displaying luminosity on the display like weather, to see what values are?

Thanks for this nice coding ;-)

**Comment by dragondaud** [comment]
Even when manually setting your location, it requires the API Key, this is because it will recalculate the offset every night at 2am to account for daylight savings changes.

I was planning to add celsius, but hadn't got around to it yet, but shouldn't take long. :)

The threshold is the value at which the clock will start reducing the brightness. Brightness is on a scale of 0-255, with zero being off and 255 being brightest. The analog port returns a value of 0-1023, with 1023 being the highest amount of light. The current reading from the LDR will be displayed on myClock's web page each time it is refreshed. When the light level drops below the threshold, it will cut the brightness in half. When the light level drops below half the threshold, it will half the brightness, again, and half again at 1/4 of the threshold.

**Comment by dragondaud** [comment]
Just pushed 0.9.15 with support for celsius, closing ticket. Reopen if you have any issues. Thanks!
